services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandbox:latest
    restart: always
    command: bundle exec puma -C config/puma.rb
    env_file:
      - .env.production
    volumes:
      - ./log:/app/log
      - ./storage:/app/storage
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-sandbox
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.well-known:/var/www/html/.well-known
      - /etc/letsencrypt/live/tabaluga.pl:/etc/letsencrypt/live/tabaluga.pl:ro
      - /etc/letsencrypt/archive/tabaluga.pl:/etc/letsencrypt/archive/tabaluga.pl:ro
    depends_on:
      - web
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
