services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: sandbox:latest
    restart: always
    command: bundle exec puma -C config/puma.rb
    env_file:
      - .env.production
    volumes:
      - ./log:/app/log
      - ./storage:/app/storage
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-sandbox
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/html/roomspace/.well-known:/var/www/html/.well-known
      - /etc/letsencrypt/live/roomspace.online:/etc/letsencrypt/live/roomspace.online:ro
      - /etc/letsencrypt/archive/roomspace.online:/etc/letsencrypt/archive/roomspace.online:ro
    depends_on:
      - web
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
